apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwlabdeployment
  namespace: cwlab-elixir-stable
  labels:
    app: cwlab
    stage: stable
spec:
  selector:
    matchLabels:
      app: cwlab
      stage: stable
  template:
    metadata:
      labels:
        app: cwlab
        stage: stable
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - name: cwlab-stable
        image: ${CICD_REGISTRY}/krini/cwlab:stable-${CICD_EXECUTION_SEQUENCE}
        env:
        - name: BUILD_NUMBER
          value: stable-${CICD_EXECUTION_SEQUENCE}
        - name: host
          value: cwlab.krini.ingress.rancher.computational.bio
        - name: mysql-host
          valueFrom:
            secretKeyRef:
              name: mysql-cwlab-stable
              key: mysql-host
        - name: mysql-password
          valueFrom:
            secretKeyRef:
              name: mysql-cwlab-stable
              key: mysql-password
        - name: mysql-username
          valueFrom:
            secretKeyRef:
              name: mysql-cwlab-stable
              key: mysql-username
        - name: ftp-host
          valueFrom:
            secretKeyRef:
              name: ftp
              key: url
        - name: ftp-username
          valueFrom:
            secretKeyRef:
              name: ftp
              key: username
        - name: ftp-password 
          valueFrom:
            secretKeyRef:
              name: ftp
              key: password
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-pv
          mountPath: /mnt/cwlab
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: shared-stable
---
apiVersion: v1
kind: Service
metadata:
  name: cwlabservice-stable
  namespace: cwlab-elixir-stable
spec:
  selector:
    app: cwlab
    stage: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cwlabingress-stable
  namespace: cwlab-elixir-stable
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  rules:
  - host: cwlab.krini.ingress.rancher.computational.bio
    http:
      paths:
      - backend:
          serviceName: cwlabservice-stable
          servicePort: 80
        path: /
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - cwlab.krini.ingress.rancher.computational.bio
    secretName: cwlab-letsencrypt-prod-private-cert # < cert-manager will store the created certificate in this secret.