# WEB_SERVER_HOST: localhost # If it shall only be available on the local machine, use "localhost".
                        # If it shall be remotely accessible from other machines on the same network, use "0.0.0.0".

WEB_SERVER_HOST: 0.0.0.0

## (2) choose the port:
WEB_SERVER_PORT: 5000 # The default is 5000, if this port is blocked choose a different one

TEMP_DIR: './scratch/temp'
WORKFLOW_DIR: './scratch/wf_dir'
EXEC_DIR: './scratch/exec'
INPUT_DIR: './scratch/input'
DB_DIR: './scratch/database'

# TEMP_DIR: '/home/epicwl/CWLab/scratch/temp'
# WORKFLOW_DIR: '/home/epicwl/CWLab/scratch/CWL'
# EXEC_DIR: '/home/epicwl/CWLab/scratch/exec'
# INPUT_DIR: '/home/epicwl/CWLab/scratch/input'
# DB_DIR: '/home/epicwl/CWLab/scratch/database'

DEBUG: True

EXEC_PROFILES:
  cwltool_local_test: # name of the exec profile
    
    # Choose the type to use:
    #   bash (Linux/MacOs), cmd (Windows)
    type: bash

    # how many times execution should be retried (default 2):
    max_retries: 2
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (prepare, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      prepare: 120
      exec: 86400
      eval: 120
      finalize: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    prepare: |
      touch "${OUTPUT_DIR}/prepare"
    exec: |
      cwltool --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages
    finalize: |
      touch "${OUTPUT_DIR}/finalize"

  cwltool_local_no_docker_test: # name of the exec profile
    
    # Choose the type to use:
    #   bash (Linux/MacOs), cmd (Windows)
    type: bash

    # how many times execution should be retried (default 3):
    max_retries: 2
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (prepare, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      prepare: 120
      exec: 86400
      eval: 120
      finalize: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    prepare: |
      touch "${OUTPUT_DIR}/prepare"
    exec: |
      cwltool --debug --no-container --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages
    finalize: |
      touch "${OUTPUT_DIR}/finalize"

  cwltool_local_singularity_test: # name of the exec profile
    
    # Choose the type to use:
    #   bash (Linux/MacOs), cmd (Windows)
    type: bash

    # how many times execution should be retried (default 3):
    max_retries: 2
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (prepare, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      prepare: 120
      exec: 86400
      eval: 120
      finalize: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    prepare: |
      touch "${OUTPUT_DIR}/prepare"
    exec: |
      cwltool --singularity --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages
    finalize: |
      touch "${OUTPUT_DIR}/finalize"


  test:
    type: bash
    timeout:
      prepare: 120
      exec: 86400
      eval: 120
      finalize: 120
    prepare: |
      touch "${OUTPUT_DIR}/prepare_test"
    exec: |
      touch "${OUTPUT_DIR}/exec_test"
      echo ${ACCESS_TOKEN} > "${LOG_FILE}"
    eval: | 
      touch "${OUTPUT_DIR}/eval"
    finalize: |
      touch "${OUTPUT_DIR}/finalizes"
  cwltool_local: # name of the exec profile
    # Choose the type to use:
    #   bash (Linux/MacOs), cmd (Windows)
    type: bash
    
    # timeout for each step in seconds 
    # if not specified the defaults are used:
    #   120 (prepare, eval, post_eval) and 86400 = 14h (exec),
    # to disable timeout set Null
    timeout:
      prepare: 120
      exec: 86400
      eval: 120
      finalize: 120

    # available variables are:
    #   - JOB_ID
    #   - RUN_ID (please note: is only unique within a job)
    #   - CWL
    #   - RUN_INPUT
    #   - OUTPUT_DIR
    #   - LOG_FILE
    exec: |
      cwltool --outdir "${OUTPUT_DIR}" "${WORKFLOW}" "${RUN_INPUT}" >> "${LOG_FILE}" 2>&1
    eval: | 
      LAST_LINE=$(tail -n 1 ${LOG_FILE})
      if [[ "${LAST_LINE}" == *"Final process status is success"* ]]
      then
        SUCCESS=True
      else
        SUCCESS=False
        ERR_MESSAGE="cwltool failed - ${LAST_LINE}"
      fi
    # Please note:
    # A SUCCESS vaiable has to be filled with true/false
    # If SUCCESS==false: the ERR_MESSAGE can provide further information 
    # such as error messages

  cwltool_python:
    type: python
    # either path to a python file (can be relative to dir of this config yaml) or
    # name of python module that is in sys.path:
    py_module: ./py_exec_profiles.py
    # class in module describing the exec steps:
    py_class: CwltoolLocalNoContainer